# Generated by Django 5.2.13 on 2026-05-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.CharField(max_length=300)),
                ('text_ar', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact message',
                'verbose_name_plural': 'Contact messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.SlugField(help_text='HTML id, e.g. home, projects, about', max_length=40, unique=True)),
                ('label_en', models.CharField(max_length=80)),
                ('label_ar', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Navigation link',
                'verbose_name_plural': 'Navigation links',
                'ordering': ['order', 'section_id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('title_en', models.CharField(max_length=200)),
                ('title_ar', models.CharField(max_length=200)),
                ('summary_en', models.TextField()),
                ('summary_ar', models.TextField()),
                ('stack_en', models.CharField(max_length=300)),
                ('stack_ar', models.CharField(max_length=300)),
                ('live_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title_en'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=120)),
                ('title_ar', models.CharField(max_length=120)),
                ('desc_en', models.TextField()),
                ('desc_ar', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title_en'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(default='Your Name', max_length=120)),
                ('name_ar', models.CharField(default='اسمك', max_length=120)),
                ('tagline_en', models.CharField(default='Full-Stack Developer', max_length=200)),
                ('tagline_ar', models.CharField(default='مطور ويب متكامل', max_length=200)),
                ('hero_title_en', models.TextField(blank=True, default='')),
                ('hero_title_ar', models.TextField(blank=True, default='')),
                ('hero_subtitle_en', models.TextField(blank=True, default='')),
                ('hero_subtitle_ar', models.TextField(blank=True, default='')),
                ('about_en', models.TextField(blank=True, default='')),
                ('about_ar', models.TextField(blank=True, default='')),
                ('contact_intro_en', models.TextField(blank=True, default='')),
                ('contact_intro_ar', models.TextField(blank=True, default='')),
                ('email', models.EmailField(default='you@example.com', max_length=254)),
                ('whatsapp', models.CharField(default='970000000000', help_text='Digits only, e.g. 970592533678', max_length=20)),
                ('github_username', models.CharField(default='yourusername', max_length=80)),
                ('github_url', models.URLField(default='https://github.com/yourusername')),
                ('hero_btn_projects_en', models.CharField(default='View Projects', max_length=60)),
                ('hero_btn_projects_ar', models.CharField(default='عرض المشاريع', max_length=60)),
                ('hero_btn_contact_en', models.CharField(default='Contact Me', max_length=60)),
                ('hero_btn_contact_ar', models.CharField(default='تواصل معي', max_length=60)),
                ('projects_title_en', models.CharField(default='Featured Projects', max_length=120)),
                ('projects_title_ar', models.CharField(default='المشاريع المميزة', max_length=120)),
                ('about_title_en', models.CharField(default='Who I Am', max_length=120)),
                ('about_title_ar', models.CharField(default='من أنا', max_length=120)),
                ('services_title_en', models.CharField(default='Services', max_length=120)),
                ('services_title_ar', models.CharField(default='الخدمات', max_length=120)),
                ('services_lead_en', models.TextField(default='I deliver clean, scalable, and maintainable software solutions.')),
                ('services_lead_ar', models.TextField(default='أقدّم حلول برمجية نظيفة وقابلة للتوسع.')),
                ('skills_title_en', models.CharField(default='Core Skills', max_length=120)),
                ('skills_title_ar', models.CharField(default='المهارات الأساسية', max_length=120)),
                ('contact_title_en', models.CharField(default='Contact', max_length=120)),
                ('contact_title_ar', models.CharField(default='تواصل', max_length=120)),
                ('contact_success_en', models.CharField(default='Your message was sent successfully. Thank you!', max_length=200)),
                ('contact_success_ar', models.CharField(default='تم إرسال رسالتك بنجاح. شكراً لك!', max_length=200)),
            ],
            options={
                'verbose_name': 'Portfolio settings',
                'verbose_name_plural': 'Portfolio settings',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
