# Generated by Django 5.2.13 on 2026-05-16 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detail_ar',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='detail_en',
            field=models.TextField(blank=True, default='', help_text='Full project description on the detail page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='details_btn_ar',
            field=models.CharField(default='التفاصيل', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='details_btn_en',
            field=models.CharField(default='Details', max_length=60),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='project_back_ar',
            field=models.CharField(default='العودة للمشاريع', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='project_back_en',
            field=models.CharField(default='Back to projects', max_length=80),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='project_gallery_title_ar',
            field=models.CharField(default='معرض الصور', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='project_gallery_title_en',
            field=models.CharField(default='Photo Gallery', max_length=120),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary_en',
            field=models.TextField(help_text='Short text on the home page card'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption_en', models.CharField(blank=True, default='', max_length=200)),
                ('caption_ar', models.CharField(blank=True, default='', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='main.project')),
            ],
            options={
                'verbose_name': 'Gallery image',
                'verbose_name_plural': 'Gallery images',
                'ordering': ['order', 'id'],
            },
        ),
    ]
