# Generated by Django 5.2.16 on 2026-07-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_detail_ar_project_detail_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpoint',
            options={'ordering': ['order'], 'verbose_name': 'نقطة تعريف', 'verbose_name_plural': 'نقاط التعريف'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'رسالة تواصل', 'verbose_name_plural': 'رسائل التواصل'},
        ),
        migrations.AlterModelOptions(
            name='navitem',
            options={'ordering': ['order', 'section_id'], 'verbose_name': 'رابط التنقل', 'verbose_name_plural': 'روابط التنقل'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', 'title_en'], 'verbose_name': 'مشروع', 'verbose_name_plural': 'المشاريع'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['order', 'id'], 'verbose_name': 'صورة معرض', 'verbose_name_plural': 'صور المعرض'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'title_en'], 'verbose_name': 'خدمة', 'verbose_name_plural': 'الخدمات'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'إعدادات الموقع', 'verbose_name_plural': 'إعدادات الموقع'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order', 'name'], 'verbose_name': 'مهارة', 'verbose_name_plural': 'المهارات'},
        ),
        migrations.AlterField(
            model_name='navitem',
            name='section_id',
            field=models.SlugField(help_text='معرف القسم في الصفحة مثل: home أو projects أو about', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='detail_en',
            field=models.TextField(blank=True, default='', help_text='الوصف الكامل في صفحة تفاصيل المشروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='summary_en',
            field=models.TextField(help_text='نص قصير يظهر على كرت المشروع في الصفحة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(default='970000000000', help_text='أرقام فقط مع رمز الدولة، مثال: 970592533678', max_length=20),
        ),
    ]
