# Generated by Django 5.2.16 on 2026-07-21 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_arabic_verbose_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='education_ar',
            field=models.CharField(blank=True, default='طالب علوم حاسوب', max_length=200, verbose_name='الدراسة (AR)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='education_en',
            field=models.CharField(blank=True, default='Computer Science Student', max_length=200, verbose_name='الدراسة (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='intro_bio_ar',
            field=models.CharField(blank=True, default='أبني منتجات ويب متكاملة ونظيفة.', max_length=280, verbose_name='نبذة قصيرة (AR)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='intro_bio_en',
            field=models.CharField(blank=True, default='Building clean full-stack web products.', help_text='سطر قصير تحت الاسم في القسم التعريفي', max_length=280, verbose_name='نبذة قصيرة (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='location_ar',
            field=models.CharField(blank=True, default='فلسطين', max_length=120, verbose_name='الموقع (AR)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='location_en',
            field=models.CharField(blank=True, default='Palestine', max_length=120, verbose_name='الموقع (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='photo',
            field=models.ImageField(blank=True, help_text='صورة مصغرة تظهر في القسم التعريفي أعلى الصفحة', null=True, upload_to='profile/', verbose_name='الصورة الشخصية'),
        ),
    ]
