# Generated by Django 5.2.16 on 2026-07-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to='projects/gallery/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='photo',
            field=models.ImageField(blank=True, help_text='صورة مصغرة تظهر في القسم التعريفي أعلى الصفحة', max_length=500, null=True, upload_to='profile/', verbose_name='الصورة الشخصية'),
        ),
    ]
